#!/usr/bin/env bash
# Installs, configures, and starts the server
# Imanol Asolo
sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
curl localhost:80
