#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59


hours=0      # Initialize hours to 0

while [ $hours -lt 13 ]; do  # Outer loop for hours (0 to 12)
    minutes=1    # Initialize minutes to 1

    while [ $minutes -lt 60 ]; do   # Inner loop for minutes (1 to 59)
        printf "%02d:%02d\n" $hours $minutes 
        minutes=$((minutes + 1))    # Increment minutes
    done | head -n 60               # Display only 60 lines (one hour)

    hours=$((hours + 1))     # Increment hours
done
