#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

for file in *; do
    if [[ $file == .* ]]; then
        continue
    fi

    # Check if the file has a dash
    if [[ $file == *-* ]]; then
        part_after_dash="${file#*-}""
    else
        part_after_dash="$file"  # No change if no dash
    fi

    echo "$part_after_dash"
done
