#!/usr/bin/env bash

if [ -f "school" ]; then   # Check if the file exists
    echo "school file exists"

    if [ -s "school" ]; then  # Check if the file is empty 
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "school" ]; then  # Check if the file is a regular file
        echo "school is a regular file"
    fi  
else
    echo "school file does not exist" 
fi
